dbURL: # db_url: postgres://postgres:indexify@vector-store/indexify
indexConfig:
  # index_store: PgVector
  # pg_vector_config:
  #   addr: postgres://postgres:indexify@vector-store/indexify
  #   m: 16
  #   efconstruction: 64
  #   efsearch: 40
metadataStorage:
  # metadata_store: postgres
  # conn_url: postgres://postgres:indexify@vector-store/indexify

blobStore:
  # allowHTTP: true
  # endpoint: http://blob-store:9000
  # credentialSecret: blob-store
  config:
    # backend: s3
    # s3:
    #   bucket: indexify
    #   region: us-east-1

api:
  enabled: true
  # replicas: 1

  image: tensorlake/indexify:stable

  ingress:
    enabled: false

  #   nodeselector:
  #     gpu: "true"

coordinator:
  enabled: true
  # replicas: 1 # must be an odd number

  image: tensorlake/indexify:stable
  #   nodeselector:
  #     gpu: "true"

  # persistence:
  #   storageClass: 'standard'

extractors:
  # - image: tensorlake/chunker:latest
  #   name: chunker
  #   replicas: 1
  #   nodeselector:
  #     gpu: "true"

extraObjects:

minio:
  enabled: false

postgresql:
  enabled: false
